declare module 'imagemin'
declare module 'imagemin-mozjpeg'
declare module 'imagemin-optipng'
declare module 'imagemin-svgo'
declare module 'imagemin-gifsicle'
declare module 'imagemin-webp'
declare module 'imagemin-avif'
declare module 'fancy-log'
